#!/bin/bash
# -*-shell-script-*-
# vim: set filetype=sh :

# COLORS!!!!
NORMAL="\[\033[00m\]"
PURPLE="\[\033[01;34m\]"
BLUE="\[\e[34m\]"
CYAN="\[\e[36m\]"
GREEN="\[\e[32m\]"

if [ ! -d "$HOME/bin/" ]; then
    mkdir "$HOME/bin/"
fi
export PATH="$HOME/bin/:$PATH"

# emacs
alias emacs='emacs -nw'

# Brew
if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi

# Grep
alias grep='grep -n'
export GREP_OPTIONS='--color=auto'
export GREP_COLOR='1;35;40'

# Tmux stuff
export TERM="xterm-256color"

# Pandoc stuff

mkmd () { # $1 input org file, $2 output md file
    pandoc -f org -t markdown -s "$1" -o "$2"
}

# Bash Stuff
export HISTCONTROL=ignoreboth:erasedups
export HISTFILESIZE=10000000

__ps1_on () {
    items_on="$(__git_ps1)"
    [[ -n "$VIRTUAL_ENV" ]] &&  items_on="$items_on (venv)"
    echo $items_on
}

export PS1="[ ${GREEN}\u${NORMAL}@${PURPLE}\h ${NORMAL}] [ ${CYAN}\w ${NORMAL}] ${BLUE}\$(__ps1_on)\n  ${GREEN}└─ \$${NORMAL}: "

export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced
alias ls='ls -lghFG'
alias cd..='cd ..'

mkcd() { mkdir -p "$@" && cd "$@"; }

# python stuff
export PATH=/usr/local/bin/ipython:$PATH
export VIRTUAL_ENV_DISABLE_PROMPT=1

vact() {
  source venv/bin/activate
}

vinst() {
    if [ ! -d 'venv' ]; then
        virtualenv -p python3 venv
        if [ -f 'requirements.txt' ]; then
            pip3 install -r requirements.txt
        fi
    fi
    vact
    pip install --upgrade pip
}

# kube stuff
__kube_ps1 () {
    CONTEXT=$(cat ~/.Kube/config | grep "current-context:" | sed "s/current-context: //")
    if [ -n "$CONTEXT" ]; then
	echo "(k8s: ${CONTEXT})"
    fi
}

# go stuff
alias ggi="go get -insecure"

export GOROOT=/usr/local/go
export GOPATH=~/Development/gocode
export PATH="$PATH:$GOROOT/bin"
export PATH="$PATH:$GOPATH/bin"

# rust?
export PATH="$HOME/.cargo/bin:$PATH"

# tree stuff
alias treejs='echo "skipping node_moudles" && tree -a -I ".git|node_modules"'
alias treepy='echo "skipping venv" && tree -a -I ".git|venv"'
alias treego='echo "skipping vender" && tree -a -I ".git|vender"'

# git stuff
alias gfap='git pull --all -p'

git_whoops () { # $1 file that is to be removed form history
    if [ -z $1 ]; then
        echo 'please list a path to remvoe from git'
    else
        echo "remving path: '$1' from git and git's history"
        git filter-branch --force --index-filter \
            "git rm -r --cached --ignore-unmatch $1" \
            --prune-empty --tag-name-filter cat -- --all
    fi
}


source "$HOME/.work"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion


source /Users/rmoon/.docker/init-bash.sh || true # Added by Docker Desktop
